#!/usr/bin/env bash
#
# train.sh -- friendly wrapper around main.py (Hydra) for training AniMerPlusPlus.
#
# main.py is a Hydra entry point: `python main.py exp_name=... experiment=... trainer=gpu launcher=local`.
# This script exists so you don't need to know Hydra's override syntax to run
# a standard training job; anything you *do* know Hydra syntax for can still
# be passed through via EXTRA_ARGS / trailing arguments.
#
# USAGE:
#   scripts/train.sh [options] [-- extra Hydra overrides]
#
# OPTIONS:
#   -e, --experiment NAME     Hydra experiment config under amr/configs_hydra/experiment/
#                              (default: AniMerPlus)
#   -n, --name NAME            Run name (Hydra exp_name), also used for the output dir
#                              (default: an autogenerated timestamp, same as Hydra's own default)
#   -l, --launcher NAME        local | slurm  (default: local)
#                              - local:  runs on this machine.
#                              - slurm:  submits via amr/configs_hydra/launcher/slurm.yaml
#                                        (submitit_slurm launcher). Edit that file for your
#                                        cluster's partition/qos/resources before using it.
#   -t, --trainer NAME         PyTorch Lightning trainer config under amr/configs_hydra/trainer/
#                              (default: gpu)
#   -d, --dry-run              Print the resolved command and exit without running it.
#   -h, --help                  Show this help and exit.
#
# Any arguments after a literal `--` are passed through verbatim as additional
# Hydra overrides (e.g. `key=value`), for anything not covered by the flags
# above -- e.g. to point at your own HORSE dataset (see amr/configs_hydra/experiment/AniMerPlus.yaml
# for all available DATASETS.* keys; DATASETS.HORSE.WEIGHT defaults to 0 -- opt in explicitly):
#
#   scripts/train.sh --name my_horse_run -- \
#       DATASETS.HORSE.WEIGHT=1 \
#       DATASETS.HORSE.ROOT_IMAGE=/path/to/horse/images \
#       DATASETS.HORSE.JSON_FILE.TRAIN=/path/to/horse/train.json \
#       DATASETS.HORSE.JSON_FILE.TEST=/path/to/horse/test.json \
#       DATASETS.ANIMAL3D.WEIGHT=0 DATASETS.CUB.WEIGHT=0 DATASETS.CTRLAVES3D.WEIGHT=0
#
# EXAMPLES:
#   # Quick local training run with defaults:
#   scripts/train.sh
#
#   # Named run, submitted to a SLURM cluster:
#   scripts/train.sh --name horse_v1 --launcher slurm
#
#   # Fast smoke test that a config/run wires up correctly (single train batch,
#   # no real epoch), useful for CI / sanity-checking after config changes:
#   scripts/train.sh --dry-run -- trainer.fast_dev_run=true
#   scripts/train.sh -- trainer.fast_dev_run=true
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

EXPERIMENT="AniMerPlus"
RUN_NAME=""
LAUNCHER="local"
TRAINER="gpu"
DRY_RUN=0
EXTRA_ARGS=()

print_help() {
    sed -n '2,/^set -euo pipefail/p' "${BASH_SOURCE[0]}" | sed '$d' | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -e|--experiment) EXPERIMENT="$2"; shift 2 ;;
        -n|--name) RUN_NAME="$2"; shift 2 ;;
        -l|--launcher) LAUNCHER="$2"; shift 2 ;;
        -t|--trainer) TRAINER="$2"; shift 2 ;;
        -d|--dry-run) DRY_RUN=1; shift ;;
        -h|--help) print_help; exit 0 ;;
        --) shift; EXTRA_ARGS+=("$@"); break ;;
        *) EXTRA_ARGS+=("$1"); shift ;;
    esac
done

if [[ "${LAUNCHER}" != "local" && "${LAUNCHER}" != "slurm" ]]; then
    echo "error: --launcher must be 'local' or 'slurm' (got: ${LAUNCHER})" >&2
    exit 1
fi

CMD=(python "${REPO_ROOT}/main.py"
    "experiment=${EXPERIMENT}"
    "trainer=${TRAINER}"
    "launcher=${LAUNCHER}")

if [[ -n "${RUN_NAME}" ]]; then
    CMD+=("exp_name=${RUN_NAME}")
fi

CMD+=("${EXTRA_ARGS[@]}")

echo "+ ${CMD[*]}"
if [[ "${DRY_RUN}" -eq 1 ]]; then
    exit 0
fi

cd "${REPO_ROOT}"
exec "${CMD[@]}"
